version: '3.1'
services:

    mariadb:
        container_name: mariadb
        image: mariadb:latest
        volumes:
            - ./var/mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=countryadmin
            - MYSQL_PASSWORD=rock4me
        ports:
            - '3306:3306'

    adminer:
        image: adminer
        links:
            - mariadb
        ports:
            - 8005:8080
