version: "3.1"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    networks:
      - global-default
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: "America/Sao_Paulo"

networks:
  global-default:
    external: true

