services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - "80:3001"
    volumes:
      - uptime-kuma:/app/data

volumes:
  uptime-kuma:
