version: "3.1"
services:
  redis:
    image: redis:alpine
    container_name: redis-single
    ports:
      - 6379:6379
    networks:
      - global-default

networks:
  global-default:
    external: true
