version: "3.1"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    networks:
      - global-default
    environment:
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=secret
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    ports:
      - 9001:9000
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs

networks:
  global-default:
    external: true

volumes:
  sonar_data:
  sonar_logs:
